import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.75
blur = true

option_as_alt = "Both"

[font]
# normal.family = "MesloLGS Nerd Font Mono"
normal.family = "JetBrainsMono Nerd Font"

size = 11

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
  { key = "K", mods = "Command", chars = "clear -x\n" },
  # work around to make <C-Tab> works in nvim -> https://github.com/alacritty/alacritty/issues/4451
  { key = "Tab", mods = "Control", chars = "\u001b[27;5;9~" },
]
